AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket + Group + Policy (permiso RW al bucket)
Resources:
  MyBucketBadi:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lab-${AWS::AccountId}-personal"
 
  MyGroupBadi:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevAcademyLabGroup
 
  MyPolicy:
    Type: AWS::IAM::Policy
    DependsOn: MyGroupBadi
    Properties:
      PolicyName: DevAcademyBucketAccess
      Groups: [ !Ref MyGroupBadi ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::lab-${AWS::AccountId}-personal"

          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource:
              - !Sub "arn:aws:s3:::lab-${AWS::AccountId}-personal/*"
 
Outputs:
  BucketName: { Value: !Ref MyBucketBadi }
  GroupName:  { Value: !Ref MyGroupBadi }
  PolicyName: { Value: !Ref MyPolicy }